# Generated by Django 3.1.dev20191210123428 on 2020-01-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('userid', models.CharField(default=None, max_length=200)),
                ('roles', models.CharField(default=None, max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('email', models.CharField(default=None, max_length=200)),
                ('section', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
