# Generated by Django 3.1.dev20191210123428 on 2020-01-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='uname',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
