# Generated by Django 3.1.dev20191210123428 on 2020-01-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0002_accesscontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='permissions',
            field=models.TextField(default=None, null=True),
        ),
    ]
