# Generated by Django 3.1.dev20191210123428 on 2020-01-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0003_auto_20200106_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='userid',
            new_name='user_id',
        ),
    ]
