# Generated by Django 3.1.dev20191210123428 on 2020-01-07 04:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0004_auto_20200107_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrol',
            name='permissions',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='audit_log',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('View Log', 'View Log')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='engagement_mgmt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All Listing', 'All Listing'), ('Listing', 'Listing'), ('Create', 'Create'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='', max_length=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='issue_mgmt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Listing', 'Listing'), ('Create', 'Create'), ('Edit Detail', 'Edit Detail'), ('Edit Reply', 'Edit Reply'), ('Edit Discussion', 'Edit Discussion'), ('Delete', 'Delete'), ('By Pass', 'By Pass')], default='', max_length=68),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='project_mgmt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Listing', 'Listing'), ('Create', 'Create'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='reporting_mgmt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Listing', 'Listing')], default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='setting',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Listing', 'Listing'), ('Create', 'Create'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='user_mgmt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Listing', 'Listing'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='', max_length=19),
            preserve_default=False,
        ),
    ]
