# Generated by Django 3.1.dev20191210123428 on 2020-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0006_auto_20200109_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='permissions',
            new_name='audit_log',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='engagement_mgmt',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='issue_mgmt',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='project_mgmt',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='reporting_mgmt',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='setting',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='user_mgmt',
            field=models.TextField(default=None, null=True),
        ),
    ]
