# Generated by Django 3.1.dev20191210123428 on 2020-01-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0007_auto_20200109_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='uid',
            new_name='uid_index',
        ),
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='uname',
            new_name='uid_uname',
        ),
    ]
