# Generated by Django 3.1.dev20191210123428 on 2020-01-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0009_auto_20200109_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrol',
            name='uid_index',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='roles',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
