# Generated by Django 3.1.dev20191210123428 on 2020-01-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclapp', '0010_auto_20200115_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='section',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
